CREATE SCHEMA musiclibrary;
SET SCHEMA=musiclibrary;

CREATE TABLE albums
(
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	album_artist VARCHAR(255) NOT NULL,
	album_title VARCHAR(255) NOT NULL,
	album_year SMALLINT NOT NULL,	
    CONSTRAINT album_pk PRIMARY KEY (id)
);

CREATE TABLE songs
(
	id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	album_id INTEGER,
	song_title VARCHAR(255) NOT NULL,
	track SMALLINT NOT NULL,	
	disc SMALLINT NOT NULL,
    CONSTRAINT song_pk PRIMARY KEY (id),
    CONSTRAINT album_fk FOREIGN KEY (album_id) REFERENCES albums (id)
);
